config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  post 'gangster', to: 'pages#gangster'
  post 'ninja', to: 'pages#ninja'
  post 'dog', to: 'pages#dog'
  post 'werewolf', to: 'pages#werewolf'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/foobar.rb
class Foobar
  def initialize(baz)
  	@foo = baz
  end
  def bar(a, b)
  	a.to_s + @foo + b[:sat].to_s
  end
end

app/controllers/concerns/person.rb
nickname = params[:name][0,5]
class Person
	def introduce
		puts params[:name] + params[:age].to_s
	end
	def birth_year()
		puts (2015-params[:age]).to_s + nickname
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def werewolf
    @first = params[:first_name].downcase
    @last = params[:last_name].downcase
    i = @first
    j = @last
    if i == 'a'
      k = 'White'
    elsif i == 'b'
      k = 'Lone'
    elsif i == 'c'
      k = 'Ravenous'
    elsif i == 'd'
      k = 'Ancient'
    elsif i == 'e'
      k = 'Magic'
    elsif i == 'f'
      k = 'Ebony'
    elsif i == 'g'
      k = 'Dark'
    elsif i == 'h'
      k = 'Savage'
    elsif i == 'i'
      k = 'Regal'
    elsif i == 'j'
      k = 'Rogue'
    elsif i == 'k'
      k = 'Scarlet'
    elsif i == 'l'
      k = 'Fierce'
    elsif i == 'm'
      k = 'Alpha'
    elsif i == 'n'
      k = 'Beautiful'
    elsif i == 'o'
      k = 'Blood'
    elsif i == 'p'
      k = 'Moon'
    elsif i == 'q'
      k = 'Loyal'
    elsif i == 'r'
      k = 'Scarred'
    elsif i == 's'
      k = 'Grey'
    elsif i == 't'
      k = 'Mystic'
    elsif i == 'u'
      k = 'Prime'
    elsif i == 'v'
      k = 'Graceful'
    elsif i == 'w'
      k = 'Majestic'
    elsif i == 'x'
      k = 'Wild'
    elsif i == 'y'
      k = 'Vengeful'
    elsif i == 'z'
      k = 'Cruel'
    else
      k = i
    end
    @first = k
    if j == 'a'
      k = 'Hunter'
    elsif j == 'b'
      k = 'Demon'
    elsif j == 'c'
      k = 'Howler'
    elsif j == 'd'
      k = 'Rain'
    elsif j == 'e'
      k = 'Red'
    elsif j == 'f'
      k = 'Shadow'
    elsif j == 'g'
      k = 'Storm'
    elsif j == 'h'
      k = 'Beast'
    elsif j == 'i'
      k = 'Bane'
    elsif j == 'j'
      k = 'Dagger'
    elsif j == 'k'
      k = 'Houng'
    elsif j == 'l'
      k = 'Fang'
    elsif j == 'm'
      k = 'Claw'
    elsif j == 'n'
      k = 'Wolf'
    elsif j == 'o'
      k = 'Crescent'
    elsif j == 'p'
      k = 'Paw'
    elsif j == 'q'
      k = 'Lupus'
    elsif j == 'r'
      k = 'Fire'
    elsif j == 's'
      k = 'Temptress'
    elsif j == 't'
      k = 'Warrior'
    elsif j == 'u'
      k = 'Rage'
    elsif j == 'v'
      k = 'Thorn'
    elsif j == 'w'
      k = 'Moon'
    elsif j == 'x'
      k = 'Lupe'
    elsif j == 'y'
      k = 'Vixen'
    elsif j == 'z'
      k = 'Omega'
    else
      k = j
    end
    @last = k
  end

  def dog
    @first = params[:first_name].downcase
    @last = params[:last_name].downcase
    i = @first
    j = @last
    if params[:gender] == '1' #if male
      if i == 'a'
        k = 'arnold'
      elsif i == 'b'
        k = 'wallace'
      elsif i == 'c'
        k = 'lewis'
      elsif i == 'd'
        k = 'reginald'
      elsif i == 'e'
        k = 'charlie'
      elsif i == 'f'
        k = 'burt'
      elsif i == 'g'
        k = 'ned'
      elsif i == 'h'
        k = 'clarence'
      elsif i == 'i'
        k = 'dick'
      elsif i == 'j'
        k = 'von'
      elsif i == 'k'
        k = 'stanley'
      elsif i == 'l'
        k = 'francis'
      elsif i == 'm'
        k = 'lawrence'
      elsif i == 'n'
        k = 'arthur'
      elsif i == 'o'
        k = 'fred'
      elsif i == 'p'
        k = 'gus'
      elsif i == 'q'
        k = 'tommy'
      elsif i == 'r'
        k = 'klaus'
      elsif i == 's'
        k = 'horace'
      elsif i == 't'
        k = 'buddy'
      elsif i == 'u'
        k = 'ollie'
      elsif i == 'v'
        k = 'gene'
      elsif i == 'w'
        k = 'doc'
      elsif i == 'x'
        k = 'douglas'
      elsif i == 'y'
        k = 'baxter'
      elsif i == 'z'
        k = 'mack'
      else
        k = i
      end
      @first = k
    else            # if female
      if i == 'a'
        k = 'dee'
      elsif i == 'b'
        k = 'mariel'
      elsif i == 'c'
        k = 'lois'
      elsif i == 'd'
        k = 'trudy'
      elsif i == 'e'
        k = 'jan'
      elsif i == 'f'
        k = 'gertie'
      elsif i == 'g'
        k = 'leigh'
      elsif i == 'h'
        k = 'kit'
      elsif i == 'i'
        k = 'frannie'
      elsif i == 'j'
        k = 'verla'
      elsif i == 'k'
        k = 'millie'
      elsif i == 'l'
        k = 'fay'
      elsif i == 'm'
        k = 'belva'
      elsif i == 'n'
        k = 'tammy'
      elsif i == 'o'
        k = 'merle'
      elsif i == 'p'
        k = 'leona'
      elsif i == 'q'
        k = 'ruth'
      elsif i == 'r'
        k = 'judith'
      elsif i == 's'
        k = 'ethel'
      elsif i == 't'
        k = 'lena'
      elsif i == 'u'
        k = 'moira'
      elsif i == 'v'
        k = 'jo'
      elsif i == 'w'
        k = 'june'
      elsif i == 'x'
        k = 'harriet'
      elsif i == 'y'
        k = 'gracie'
      elsif i == 'z'
        k = 'venna'
      else
        k = i
      end
      @first = k
    end
    if j == 'a'     #last name
      k = 'Howell'
    elsif j == 'b'
      k = 'McGillicuddy'
    elsif j == 'c'
      k = 'Mertz'
    elsif j == 'd'
      k = 'Petrie'
    elsif j == 'e'
      k = 'Rogers'
    elsif j == 'f'
      k = 'Sullivan'
    elsif j == 'g'
      k = 'Burr'
    elsif j == 'h'
      k = 'Wynn'
    elsif j == 'i'
      k = 'Fine'
    elsif j == 'j'
      k = 'Cunningham'
    elsif j == 'k'
      k = 'Cleaver'
    elsif j == 'l'
      k = 'Clark'
    elsif j == 'm'
      k = 'Hitchcock'
    elsif j == 'n'
      k = 'Cabot'
    elsif j == 'o'
      k = 'Howard'
    elsif j == 'p'
      k = 'Waring'
    elsif j == 'q'
      k = 'Berle'
    elsif j == 'r'
      k = 'Como'
    elsif j == 's'
      k = 'Karloff'
    elsif j == 't'
      k = 'Klugman'
    elsif j == 'u'
      k = 'Crockett'
    elsif j == 'v'
      k = 'Winkler'
    elsif j == 'w'
      k = 'King'
    elsif j == 'x'
      k = 'Lear'
    elsif j == 'y'
      k = "O'connor"
    elsif j == 'z'
      k = 'Ricardo'
    else
      k = j
    end
    @last = k
  end

  def gangster
    @first = params[:first_name].downcase
    @text = ""
    @first.split("").each do |i|
      if i == 'a'
        k = 'sha'
      elsif i == 'b'
        k = 'ni'
      elsif i == 'c'
        k = 'ki'
      elsif i == 'd'
        k = 'que'
      elsif i == 'e'
        k = 'nay'
      elsif i == 'f'
        k = 'qui'
      elsif i == 'g'
        k = 'ti'
      elsif i == 'h'
        k = 'la'
      elsif i == 'i'
        k = 'kay'
      elsif i == 'j'
        k = 'ri'
      elsif i == 'k'
        k = 'barack'
      elsif i == 'l'
        k = 'obama'
      elsif i == 'm'
        k = 'di'
      elsif i == 'n'
        k = 'ta'
      elsif i == 'o'
        k = 'ee'
      elsif i == 'p'
        k = 'ray'
      elsif i == 'q'
        k = 'cli'
      elsif i == 'r'
        k = 'gurl'
      elsif i == 's'
        k = 'na'
      elsif i == 't'
        k = 'qua'
      elsif i == 'u'
        k = 'kwa'
      elsif i == 'v'
        k = 'ise'
      elsif i == 'w'
        k = 'fi'
      elsif i == 'x'
        k = 'quee'
      elsif i == 'y'
        k = 'mi'
      elsif i == 'z'
        k = 'si'
      else
        k = i
      end
      @text += k
    end
  end

  def ninja
    @first = params[:first_name].downcase
    @text = ""
    @first.split("").each do |i|
      if i == 'a'
        k = 'ka'
      elsif i == 'b'
        k = 'zu'
      elsif i == 'c'
        k = 'mi'
      elsif i == 'd'
        k = 'te'
      elsif i == 'e'
        k = 'ku'
      elsif i == 'f'
        k = 'lu'
      elsif i == 'g'
        k = 'ji'
      elsif i == 'h'
        k = 'ri'
      elsif i == 'i'
        k = 'ki'
      elsif i == 'j'
        k = 'zu'
      elsif i == 'k'
        k = 'me'
      elsif i == 'l'
        k = 'ta'
      elsif i == 'm'
        k = 'rin'
      elsif i == 'n'
        k = 'to'
      elsif i == 'o'
        k = 'mo'
      elsif i == 'p'
        k = 'no'
      elsif i == 'q'
        k = 'ke'
      elsif i == 'r'
        k = 'shi'
      elsif i == 's'
        k = 'ari'
      elsif i == 't'
        k = 'chi'
      elsif i == 'u'
        k = 'do'
      elsif i == 'v'
        k = 'ru'
      elsif i == 'w'
        k = 'mei'
      elsif i == 'x'
        k = 'na'
      elsif i == 'y'
        k = 'fu'
      elsif i == 'z'
        k = 'zi'
      else
        k = i
      end
      @text += k
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Name Generator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/dog.html.erb
<head>
<style media = 'screen' type = 'text/css'>

body {
	background-color: black;
	padding: 0px 20px;
}
img {
	width: 300px;
	height: 300px;
}

.new_name {
	font-family: "Comic Sans MS";
	color: White;
	text-align: center;
}

.border1 {
	position: top left;
	font-size: 0;
}

.border2 {
	font-size: 0;
}
</style>

	<title>What's your pretentious dog name?</title>
</head>
<body>
	<div class="border1">
		<img src="http://canineowners.com/wp-content/uploads/2014/09/Selection_071.png">
		<img src="http://barkpost-assets.s3.amazonaws.com/wp-content/uploads/2013/05/tumblr_mg81ki58GQ1rcn7ino1_500_large.jpg">
		<img src="http://7-themes.com/data_images/out/5/6784229-cute-dog-with-glasses-wallpaper.jpg">
		<img src="http://media.nyusu.fm/ranking/option/940/27899.jpg">

	</div>

	<div class="original_name">
		<h4>Your Name:</h4>
	</div>
	<div class="new_name">
		<h1>Pretentious Dog Name: <%= @first.capitalize %> <%= @last.capitalize %></h1>

	<div class="border2">
		<img src="http://www.apartmentguide.com/blog/wp-content/uploads//2011/08/istock_000004809250xsmall1.jpg">
		<img src="http://www.mailinmobile.com/blog/wp-content/uploads/2014/09/Dogs-Cell-Phones.jpg">
		<img src="http://blog.petcarerx.com/wp-content/uploads/2013/08/Pampered-Dog-Blog.jpg">
		<img src="http://s2.favim.com/orig/37/bulldog-cute-puppy-swing-Favim.com-300662.jpg">
	</div>
</body>

app/views/pages/gangster.html.erb
<head>

<style media = 'screen' type = 'text/css'>
	body {
		background-image: url("http://phandroid.s3.amazonaws.com/wp-content/uploads/2015/01/bricks-5.jpg");
		background-color: #cccccc;
	}
	img {
	width: 200px;
	height: 200px;
}
.name {
	font-family: 'Arvo', serif;
}
.cover {
	text-align: center;
	font-family: 'Arvo', serif;
	color: white;
    text-shadow:
    -1px -1px 0 #000,
    1px -1px 0 #000,
    -1px 1px 0 #000,
    1px 1px 0 #000;
    line-height: 15em;
}
.random {
	margin: 0 auto;
	width: 600px;
	background-color: #D6D3DB;
	font-family: 'Arvo', serif;
	padding: 20px 6px;
	border-radius: 3%;
}
  

</style>


	<title>Gangster Name</title>

	<link href='https://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="cover">
		<h1 class="name"><font size='20'>Gangster Name Generator</h1>
	</div>
	<div class="random">
		<p1><font size="5">Your gangster name is <%= @text.capitalize %></font></p1>
	</div>
	<img src="http://i735.photobucket.com/albums/ww352/Dez21/Money/GreenDollarSign.gif"/> 
	<img src="http://rs767.pbsrc.com/albums/xx315/Alexanderchavez_2009/tumblr_lluja04WC21qdb5i8.gif~c200"/>
	<img src="http://www.gifwave.com/media/559099_oh-no-you-didnt-movies-harry-potter-voldemort-ghetto.gif" height='213px' width='500'/>
	<img src="http://stream1.gifsoup.com/view1/1247309/grillz-o.gif"/>
	<img src="http://www.clipartbest.com/cliparts/9Tz/onM/9TzonMEXc.gif"/>
	<img src="http://img3.wikia.nocookie.net/__cb20110731053214/potcoplayers/images/b/be/Rotating_gold_dollar_sign.gif"/>
	<img src="http://static.tumblr.com/ofcyqmq/zQnlkhsol/gangster.gif"/>
</body>

app/views/pages/home.html.erb
<head>
<style media = 'screen' type = 'text/css'>

h1 {
  text-align: center;
  font-family: 'Comic Sans MS';
  text-shadow: 3px 3px #FFDAF6;
}

body {
  /*background-color:#ECFAEC;*/
  background-image: url('https://s-media-cache-ak0.pinimg.com/236x/5e/eb/b7/5eebb709baa68ed2bcede64004a14900.jpg');
}

.boxed {
  border: 5px solid #6A828B;
  padding: 25px;
  background-color: #E7F1F5;
  box-shadow: 4px 4px #A7CCDA;
}

.boxed2 {
  border: 2px solid #6A828B;
  padding: 25px;
  background-color: #F7FAFC;
}

</style>
</head>

<body>
  <h1 class='cover' style="color:#A22082"> Welcome to Name Generator! </h1>

  <h1>
    <div class = 'boxed'>
      <div class = 'boxed2'>
        <%= form_tag gangster_path do %>
          <%= text_field_tag 'first_name', nil,  placeholder: "Your Name" %>
          <%= submit_tag "Generate Gangster Name!" %>
          <img src ="http://cliparts.co/cliparts/ATb/K76/ATbK76qyc.gif" height='60px' width = '40px' />
        <% end %>
      </div>
    <div class = 'boxed2'>
      <%= form_tag ninja_path do %>
        <img src ="http://1.viki.io/d/1863c/8b75dc48c9.gif" height='60px' width = '80px' />
        <%= text_field_tag 'first_name', nil, placeholder: "Your Name" %>
        <%= submit_tag "Generate Ninja Name!" %>
      <% end %>
      </div>
    <div class = 'boxed2'>
      <%= form_tag dog_path do %>
        <%= select_tag(:gender, options_for_select([['Male',1],['Female',2]])) %>
        <%= text_field_tag 'first_name',nil,placeholder: "First Name Initial" %>
        <%= text_field_tag 'last_name',nil,placeholder: "Last Name Initial" %>
        <%= submit_tag "Generate Pretentious Dog Name!" %>
        <img src ="http://dogbreedinfo.us/images/Dog.gif" height='60px' width = '55px' />
      <% end %>
      </div>
    <div class = 'boxed2'>
      <%= form_tag werewolf_path do %>
        <img src ="http://static.fjcdn.com/pictures/Dammit+moon+moon+oh+moon+moon_c67718_4562382.png" height='120px' width = '180px' />
        <%= text_field_tag 'first_name',nil,placeholder: "First Name Initial" %>
        <%= text_field_tag 'last_name',nil,placeholder: "Last Name Initial" %>
        <%= submit_tag "Generate Werewolf Name!" %>
      <% end %>
      </div>
    </div>
  </h1>
</body>

app/views/pages/ninja.html.erb
<head>
<style media = 'screen' type = 'text/css'>
/*body {
	background-color: gray;
}*/
.link {
	padding: 10px 400px;
	color: white;
}

.cover {
	text-align: center;
	background-image: url("http://www.tiny-ninja.com/layout/ninja.png");
	width: 1000px;
	height: 700px;
	background-position: 200px 150px;
	background-repeat: no-repeat;
	color: Red;
}

.original_name {
	font-family: "Comic Sans MS";
	color: black;
}
.new_name {
	font-family: "Comic Sans MS";
	color: #4B0082;
}

.boxed {
  border: 5px solid #8C5DAF;
  padding: 25px;
  background-color: #DED1E8;
  box-shadow: 4px 4px #DED1E8;
}

</style>

<title>What's your ninja name?</title>
</head>
<body link = "white" background ='http://1.bp.blogspot.com/-uhCqE3LElYI/UymXeOqKXTI/AAAAAAAAMJg/Nts0kcDNlPc/s1600/CLA018_BACK.jpg'>
	<div class="cover">
		<h5 class="original_name">Your Name: <%= @first.capitalize%></h1>
		<h2 class="new_name boxed">Ninja Name: <%= @text.capitalize %></h1>
	</div>
</body>

app/views/pages/stringify.html.erb
<img src="http://www.clipartbest.com/cliparts/ncB/Xjz/ncBXjzb7i.jpg" width='60px' height='60px'>
<p><%= @first.capitalize%>, your ghetto name is <%= @text.capitalize %></p>
<img src="http://www.clipartbest.com/cliparts/ncB/Xjz/ncBXjzb7i.jpg" width='60px' height='60px'>

app/views/pages/werewolf.html.erb
<head>

<style media = 'screen' type = 'text/css'>

img {
	width: 200px;
	height: 200px;
}
.name {
	font-family: 'Arvo', serif;
}
.cover {
	text-align: center;
	font-family: 'Arvo', serif;
	color: white;
    text-shadow:
    -1px -1px 0 #000,
    1px -1px 0 #000,
    -1px 1px 0 #000,
    1px 1px 0 #000;
    line-height: 15em;
}
.random {
	margin: 0 auto;
	width: 600px;
	background-color: #D6D3DB;
	font-family: 'Arvo', serif;
	padding: 20px 6px;
	border-radius: 3%;
}
</style>

	<title>Werewolf Name</title>
	<style>
	body {
		background-image: url("https://scontent-sjc2-1.xx.fbcdn.net/hphotos-xap1/t31.0-8/12138481_847770325320794_9044768570476113122_o.jpg");
		background-color: #cccccc;
	}
	</style>
	<link href='https://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="cover">
		<h1 class="name"><font size='20'>Werewolf Name Generator</h1>
	</div>
	<div class="random">
		<p1><font size="5">Your werewolf name is <%= @first.capitalize %> <%= @last.capitalize %></font></p1>
	</div>
</body>